# Generated by Django 3.2.7 on 2021-09-08 18:29

from django.db import migrations, models
import products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=products.utils.generate_sku, max_length=254, null=True),
        ),
    ]
