# Generated by Django 3.2.7 on 2021-10-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
