# Generated by Django 3.2.7 on 2021-10-16 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_product_rates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rates',
        ),
        migrations.AddField(
            model_name='product',
            name='rates',
            field=models.ManyToManyField(related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
