# Generated by Django 3.2.7 on 2021-10-17 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
