# Generated by Django 3.2.7 on 2021-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_average',
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
